name: Build LaTeX document
on:
  push:
    branches: 
      - main
    paths:
      - 'source.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Replace the VERSION placeholder
        run: |
          sed -i "s/VERSION/${GITHUB_SHA::6}/" source.tex
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: source.tex
          
      - name: Commit the compiled pdf output
        run: |
          mv source.pdf compiled.pdf
          git config user.name "Github Actions"
          git config user.email "<>"
          git add compiled.pdf
          git commit -m "Compile pdf for the commit [${GITHUB_SHA::6}]"
          git push origin main
